# SOME DESCRIPTIVE TITLE.
# Copyright (C) YEAR ORGANIZATION
# FIRST AUTHOR <EMAIL@ADDRESS>, YEAR.
#
msgid ""
msgstr ""
"Project-Id-Version: \n"
"POT-Creation-Date: 2017-05-11 22:55+0300\n"
"PO-Revision-Date: 2017-05-11 22:56+0300\n"
"Language-Team: \n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=UTF-8\n"
"Content-Transfer-Encoding: 8bit\n"
"Generated-By: pygettext.py 1.5\n"
"X-Generator: Poedit 1.8.7.1\n"
"Last-Translator: \n"
"Plural-Forms: nplurals=2; plural=(n != 1);\n"
"Language: en\n"

#: VM/BDL/BDCon.py:19 VM/UI/ChoosingItem.py:31
msgid "There are no items to sell"
msgstr "There are no items to sell"

#: VM/BDL/BDCon.py:20 VM/UI/ChoosingItem.py:32
msgid "Message"
msgstr "Message"

#: VM/BDL/DataSources/MySQLDB.py:60 VM/BDL/DataSources/MySQLDB.py:76
#: VM/BDL/DataSources/MySQLDB.py:91 VM/BDL/DataSources/MySQLDB.py:107
#: VM/BDL/DataSources/MySQLDB.py:123 VM/BDL/DataSources/MySQLDB.py:178
#: VM/Printer/PrnDK350.py:34 VM/Vending.py:40
msgid "Error"
msgstr "Error"

#: VM/BDL/DataSources/MySQLDB.py:60 VM/BDL/DataSources/MySQLDB.py:91
#: VM/BDL/DataSources/MySQLDB.py:107 VM/BDL/DataSources/MySQLDB.py:123
msgid "Database connection failed"
msgstr "Database connection failed"

#: VM/BDL/DataSources/MySQLDB.py:76
msgid "There is errors in the configuration file. No section."
msgstr "There is errors in the configuration file. No section."

#: VM/BDL/DataSources/MySQLDB.py:178
msgid "Database error"
msgstr "Database error"

#: VM/KP/KPProvider.py:89
msgid "Error in recognition of note"
msgstr "Error in recognition of note"

#: VM/KP/KPProvider.py:103
msgid "Protocol version's setting error"
msgstr "Protocol version's setting error"

#: VM/KP/KPProvider.py:110
msgid "Error in request of notes' channels"
msgstr "Error in request of notes' channels"

#: VM/KP/KPProvider.py:119
msgid "Error in notes' denomination reading"
msgstr "Error in notes' denomination reading"

#: VM/KP/KPProvider.py:126
msgid "Error in setting channels of notes receiving"
msgstr "Error in setting channels of notes receiving"

#: VM/KP/KPProvider.py:133
msgid "Engage procedure error"
msgstr "Engage procedure error"

#: VM/KP/KPProvider.py:148
msgid "Device synchronization failed"
msgstr "Device synchronization failed"

#: VM/KP/KPProvider.py:280
msgid "Note receiver's port is not found"
msgstr "Note receiver's port is not found"

#: VM/KP/KPProvider.py:294
msgid "Devise not responding"
msgstr "Devise not responding"

#: VM/Printer/PrnDK350.py:34
msgid "Configuration file error. No printer's section."
msgstr "Configuration file error. No printer's section."

#: VM/UI/GivingOutItem.py:18
msgid "Wait for delivery..."
msgstr "Wait for delivery..."

#: VM/UI/GivingOutItem.py:22
msgid "Delivery error. Call techsupport, please."
msgstr "Delivery error. Call techsupport, please."

#: VM/UI/ScanBrelok.py:38
msgid "Press the button \"Scan\""
msgstr "Press the button \"Scan\""

#: VM/UI/ScanBrelok.py:39
msgid "and enclose your key to the scanner"
msgstr "and enclose your key to the scanner"

#: VM/UI/ScanBrelok.py:40
msgid "Scanning..."
msgstr "Scanning..."

#: VM/UI/ScanBrelok.py:41
msgid "Scanning failed"
msgstr "Scanning failed"

#: VM/UI/ScanBrelok.py:42
msgid "Scan"
msgstr "Scan"

#: VM/Vending.py:39
msgid "Database connection error"
msgstr "Database connection error"
